version: '3.9'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 5081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admdb
      WORDPRESS_DB_PASSWORD: ipM$T1vd@1H@0i
      WORDPRESS_DB_NAME: wpdb
    networks:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini 
    links:
      - db:db
      
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: admdb
      MYSQL_PASSWORD: ipM$T1vd@1H@0i
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wordpress
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    networks:
      - wordpress
      
volumes:
  wordpress:
  db:

networks:
  wordpress:
