version: '3.1'

services:

  wordpress:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${WEB_SERVER_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admdb
      WORDPRESS_DB_PASSWORD: ygig1&KYUAQ^%
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      
  db:
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admdb
      MYSQL_PASSWORD: ygig1&KYUAQ^%
      MYSQL_ROOT_PASSWORD: xK^d$oZB1cG4KP
    networks:
      - wordpress
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

networks:
  wordpress:
